### ISSUE TITLE
Icons don't change color in fixed start menu

### ISSUE THREAD

**Issue by Mioni** [passionate-coder/Classic-Start#48]
If I change the color of windows the icons do not update the color the icons set in the start menu. This happens only in the icons that are fixed in the start menu. 
My windows is blue color now, look these icons:
![capture](https://user-images.githubusercontent.com/6830783/43009180-4fd20f5e-8c13-11e8-891a-36f1435db189.PNG)

Windows 1803.

**Comment by ge0rdi** [comment]
What start menu style do you use?
And what skin?

Could you post screenshot of whole start menu?

**Comment by Mioni** [comment]
Use Windows 7 Style and skin Windows 8
![capture](https://user-images.githubusercontent.com/6830783/43013228-a32ef4f4-8c1e-11e8-84b5-699a847d16f9.PNG)
Other problem Grover Podcast don't show icon.

**Comment by ge0rdi** [comment]
> This happens only in the icons that are fixed in the start menu.

I guess you meant icons _pinned_ to start menu.
Because I can replicate the same behavior with them. They have _some_ background color, no matter of system accent color.

Pinned items are in fact `LNK` files and Classic Start is getting icons from those files by using system API.

Try to _right click_ on given problematic icon and pick _Properties_. You should see the same background color as displayed in Classic Start.

It seems it is cached somewhere. Like first time you'll ever get given icon, system accent color is used as background and this is then cached.

That's said it may be not exactly an issue with Classic Start. It seems to be system-wide issue.

Not sure what to do with it though :(

**Comment by Mioni** [comment]
Pinned and fixed is the same! 😋 
It's ok! thank you!
